# Generated by Django 4.1.2 on 2022-12-28 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0024_remove_readingupdate_reading_delete_reading_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Reading',
                    fields=[
                        ('id',
                         models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start')),
                        ('end', models.DateTimeField(blank=True, default=None, null=True, verbose_name='End')),
                        ('edition',
                         models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE,
                                           to='books.edition')),
                        ('reader',
                         models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'books_reading',
                    },
                ),
                migrations.CreateModel(
                    name='ReadingUpdate',
                    fields=[
                        ('id',
                         models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('page', models.IntegerField(default=0, verbose_name='Page')),
                        ('date',
                         models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date')),
                        ('reading',
                         models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readings.reading')),
                    ],
                    options={
                        'db_table': 'books_readingupdate',
                    },
                ),
            ],
            database_operations=[]  # actually, do nothing
        )
    ]
