# Generated by Django 4.1.2 on 2023-01-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='current_page',
            field=models.IntegerField(default=0),
        ),
    ]
