# Generated by Django 4.1.7 on 2023-11-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("readings", "0002_reading_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="reading",
            name="deadline",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Deadline"
            ),
        ),
        migrations.AddField(
            model_name="reading",
            name="deadline_percent",
            field=models.PositiveIntegerField(
                blank=True, default=100, verbose_name="Deadline percent"
            ),
        ),
    ]
