# Generated by Django 3.0.3 on 2020-08-07 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_userpreferences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreferences',
        ),
    ]
