# Generated by Django 3.0.7 on 2020-10-10 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_reading_readingupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingupdate',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
