# Generated by Django 3.1.3 on 2020-11-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_readingupdate_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookEndEvent',
        ),
    ]
