# Generated by Django 3.1.3 on 2020-11-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_delete_bookstartevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageUpdateEvent',
        ),
    ]
