# Generated by Django 3.1.3 on 2020-11-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_delete_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ordered',
        ),
    ]
