# Generated by Django 3.1.3 on 2020-11-18 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_remove_book_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=16, verbose_name='ISBN')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('year', models.IntegerField(default=1, verbose_name='Year')),
                ('pages', models.IntegerField(default=1, verbose_name='Pages')),
                ('book', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
