# Generated by Django 3.1.3 on 2020-11-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_bookcopy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
    ]
