# Generated by Django 3.1.3 on 2020-11-25 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_remove_book_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='edition',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='books.edition'),
        ),
    ]
