# Generated by Django 3.1.3 on 2020-11-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_reading_edition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='book',
        ),
    ]
